version: 2

registries:
  aws-ecr-docker:
    type: docker-registry
    url: 414700354900.dkr.ecr.us-east-1.amazonaws.com
    username: ${{ secrets.CORE_SHR_ECR_AWS_ACCESS_KEY_ID }}
    password: ${{ secrets.CORE_SHR_ECR_AWS_ACCESS_SECRET_KEY }}
  azdo-artifacts-pypi:
    type: python-index
    url: https://pkgs.dev.azure.com/gboticario/_packaging/
    username: ${{ github.actor }}
    password: ${{ secrets.AZDO_AZUREARTIFACTS_CT }}
    replaces-base: true
  github-packages-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GHA_PACKAGES }}

updates:
  - package-ecosystem: docker
    directory: /dockerfiles
    open-pull-requests-limit: 10
    registries:
      - aws-ecr-docker
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    registries:
      - github-packages-npm
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    insecure-external-code-execution: allow
    open-pull-requests-limit: 10
    registries:
      - azdo-artifacts-pypi
    schedule:
      interval: weekly
