app:
  env:
    - name: NEW_RELIC_ENV
      value: "hml"
    - name: "NEW_RELIC_CONFIG_FILE"
      value: "./newrelic.ini"
    - name: "PYTHONPATH"
      value: "."
    - name: "PYTHONUNBUFFERED"
      value: "1"
    - name: "PYTHONDONTWRITEBYTECODE"
      value: "1"
    - name: "POETRY_VIRTUALENVS_CREATE"
      value: "false"
    - name: "LOG_LEVEL_ENABLED"
      value: "ERROR"
    - name: DOCKER_CMD
      value: newrelic-admin run-program gunicorn agenda_testes_e2e.main:app -b
        0.0.0.0:3000 --workers 2 -k uvicorn.workers.UvicornWorker
  probe:
    path: /v1/healthcheck
    port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 60
  name: "agenda-testes-e2e"
  valueStream: "produto-financeiro"
  namespace: "processamento"
  environment: hml
  default_tags:
    tier: backend
    squad: "processamento-agenda"
    product: "processamento"
  secretStore:
    enabled: true
    region: us-east-1
    keys:
      - secretName: global-secret-newrelic-license-key
        envName: NEW_RELIC_LICENSE_KEY
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::020805263868:role/agenda-testes-e2e-role-application
  ingress:
    scope: private
    wafArn:
      "arn:aws:wafv2:us-east-1:020805263868:regional/webacl/acl-backend/b12e5\
      573-cfc3-44fe-b8a0-4aabf5165e03"
  replicas: 1
  image:
    repository: "815618849747.dkr.ecr.us-east-1.amazonaws.com/agenda-testes-e2e"
  service:
    enabled: true
  port: 3000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  podDisruptionBudget:
    enabled: true
  resources:
    cpu: 200m
    memory: 256Mi
  nodeSelector:
    kubernetes.io/arch: arm64
  tolerations:
    - key: "arm"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
