run-name: DevSecOps
name: DevSecOps
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  devsecops:
    uses: grupoboticario/actions-devsecops-workflows/.github/workflows/devsecops.yml@v0
    secrets:
      azdo-azureartifacts-ct: ${{ secrets.AZDO_AZUREARTIFACTS_CT }}
